// <auto-generated />
namespace TDC_Invoice_Generator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakeStatusFieldLengthShort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeStatusFieldLengthShort));
        
        string IMigrationMetadata.Id
        {
            get { return "202109131857551_MakeStatusFieldLengthShort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
