// <auto-generated />
namespace TDC_Invoice_Generator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStatusToDeliveryNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStatusToDeliveryNote));
        
        string IMigrationMetadata.Id
        {
            get { return "202109131808496_AddStatusToDeliveryNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
